backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "dist/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images"


